# Generated by Django 2.2 on 2019-04-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='current_membership',
            field=models.BooleanField(default=False),
        ),
    ]
