# Generated by Django 2.2 on 2019-04-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_current_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
    ]
