# Generated by Django 2.2 on 2019-04-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20190416_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='card_number',
            field=models.CharField(default=999, max_length=4),
        ),
    ]
